import pyautogui
import time
i=(input("введите кликер,запрос,создание папки "))
if i=="кликер":
    time.sleep(1)
    pyautogui.moveTo(330,760)
    pyautogui.click(button ="left")
    pyautogui.moveTo(600,350)
    while(True):
        pyautogui.click(button = "left")
elif i=="запрос":
    ir=(input("Введите что нужно найти "))
    time.sleep(1)
    pyautogui.moveTo(150,760)
    pyautogui.click(button = "left")
    time.sleep(1)
    pyautogui.moveTo(1150,10)
    pyautogui.click(button = "left")
    time.sleep(1)
    pyautogui.moveTo(600,140)
    pyautogui.click(button = "left")
    time.sleep(1)
    pyautogui.hotkey('ctrl',"a")
    time.sleep(1)
    pyautogui.hotkey('delete')
    time.sleep(1)
    pyautogui.moveTo(600,140)
    pyautogui.click(button = "left")
    time.sleep(1)
    pyautogui.write(ir, interval=0.5)
    pyautogui.press('enter')
elif i=="создание папки":
    im=(input("Введите название папки "))
    time.sleep(1)
    pyautogui.moveTo(330,760)
    time.sleep(2)
    pyautogui.click(button ="left")
    time.sleep(1)
    pyautogui.moveTo(700,60)
    time.sleep(2)
    pyautogui.click(button = "right")
    time.sleep(1)
    pyautogui.moveTo(750,270)
    pyautogui.click(button = "right")
    time.sleep(1)
    pyautogui.dragTo(1050,270, button='left')
    pyautogui.click(button ="left")
    time.sleep(1)
    pyautogui.write(im,interval=0.5)
    pyautogui.press('enter')
